table_corners_b:
  _target_: isaaclab.managers.ObservationTermCfg
  func: gear_sonic.envs.manager_env.mdp:table_corners_b
  params:
    command_name: "motion"
    table_size: ${manager_env.config.table_size}
